name: Release & Publish

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version Bump Type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major

permissions:
  contents: write # Required to push the version commit and create releases
  id-token: write # Required if you use provenance publishing (optional)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Important: Fetch all history for git describe/log to work
          ssh-key: ${{ secrets.RELEASE_DEPLOY_KEY }}

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Run Tests
        run: npm run test

      - name: Configure Git
        run: |
          git config --global user.name "google-adk[bot]"
          git config --global user.email "google-adk[bot]@users.noreply.github.com"

      - name: Update Core package version
        run: echo "NEW_TAG=$(node ./scripts/update_version.js --package=core --version=${{ inputs.version_type }})" >> $GITHUB_ENV

      - name: Update Dev package version
        run: node ./scripts/update_version.js --package=dev --version=${{ env.NEW_TAG }}

      - name: Update Root package version
        run: node ./scripts/update_version.js --package= --version=${{ env.NEW_TAG }}

      - name: Commit version changes
        run: git add . && git commit -m "Bump version to v${{ env.NEW_TAG }}"

      - name: Create version tag
        run: git tag -a v${{ env.NEW_TAG }} -m "v${{ env.NEW_TAG }}"

      - name: Push changes
        run: git push origin --follow-tags

      - name: Publish Core package to NPM
        working-directory: ./core
        run: npm publish --access=public --registry https://wombat-dressing-room.appspot.com/@google/adk/_ns
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WOMBAT_CORE_TOKEN }}

      - name: Publish Dev package to NPM
        working-directory: ./dev
        run: npm publish --access=public --registry https://wombat-dressing-room.appspot.com/@google/adk-devtools/_ns
        env:
          NODE_AUTH_TOKEN: ${{ secrets.WOMBAT_DEVTOOLS_TOKEN }}